-- MySQL Script generated by MySQL Workbench
-- Sat 18 Apr 2020 05:58:33 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pharmacy` ;

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmacy` ;
USE `pharmacy` ;

-- -----------------------------------------------------
-- Table `pharmacy`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`user` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `username` VARCHAR(32) NOT NULL COMMENT '用户名',
  `password` VARCHAR(128) NOT NULL COMMENT '密码',
  `name` VARCHAR(6) NULL COMMENT '姓名',
  `gender` VARCHAR(1) NULL COMMENT '性别',
  `phone` VARCHAR(11) NULL COMMENT '手机号码',
  `email` VARCHAR(100) NULL COMMENT '电子邮箱',
  `enable` INT NOT NULL DEFAULT 1 COMMENT '是否启用，1为启用，0为停用',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_UNIQUE` (`username` ASC))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `pharmacy`.`repository`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`repository` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`repository` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `name` VARCHAR(10) NOT NULL COMMENT '仓库名称',
  `address` VARCHAR(45) NOT NULL COMMENT '仓库地址',
  `note` VARCHAR(45) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`supplier` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(45) NOT NULL COMMENT '名称',
  `address` VARCHAR(45) NULL COMMENT '地址',
  `postcode` VARCHAR(45) NULL COMMENT '邮编',
  `telephone` VARCHAR(45) NULL COMMENT '电话',
  `email` VARCHAR(45) NULL COMMENT '电子邮箱',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`medicine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`medicine` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`medicine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `supplier_id` INT NOT NULL,
  `manufacture_date` DATE NULL,
  `buying_price` DECIMAL(9,2) NOT NULL COMMENT '采购价',
  `price` DECIMAL(9,2) NOT NULL COMMENT '售价',
  `shelf_life` INT NOT NULL COMMENT '保质期，单位：天',
  `specifications` VARCHAR(45) NOT NULL COMMENT '规格',
  `manufacturer` VARCHAR(45) NOT NULL COMMENT '制造商',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`code` ASC),
  INDEX `fk_medicine_supplier1_idx` (`supplier_id` ASC),
  CONSTRAINT `fk_medicine_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `pharmacy`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`storage` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`storage` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `medicine_id` INT NOT NULL COMMENT '药物主键',
  `repository_id` INT NOT NULL COMMENT '仓库主键',
  `limit` INT NOT NULL COMMENT '存储上限',
  `inventory` INT NOT NULL DEFAULT 0 COMMENT '目前库存',
  PRIMARY KEY (`id`),
  INDEX `fk_storage_medicine_idx` (`medicine_id` ASC),
  INDEX `fk_storage_repository1_idx` (`repository_id` ASC),
  UNIQUE INDEX `medicine_id_repository_id_UNIQUE` (`medicine_id` ASC, `repository_id` ASC),
  CONSTRAINT `fk_storage_medicine`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `pharmacy`.`medicine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storage_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `pharmacy`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`iorecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`iorecord` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`iorecord` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `medicine_id` INT NOT NULL COMMENT '药物表主键',
  `repository_id` INT NOT NULL COMMENT '仓库表主键',
  `recorder_id` INT NOT NULL COMMENT '记录/操作员',
  `type` INT NOT NULL COMMENT '类型，1为入，0为出',
  `quantity` INT NOT NULL COMMENT '数量',
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录日期',
  PRIMARY KEY (`id`),
  INDEX `fk_iorecord_medicine1_idx` (`medicine_id` ASC),
  INDEX `fk_iorecord_repository1_idx` (`repository_id` ASC),
  INDEX `fk_iorecord_user1_idx` (`recorder_id` ASC),
  CONSTRAINT `fk_iorecord_medicine1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `pharmacy`.`medicine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iorecord_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `pharmacy`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iorecord_user1`
    FOREIGN KEY (`recorder_id`)
    REFERENCES `pharmacy`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '入/出库记录表';


-- -----------------------------------------------------
-- Table `pharmacy`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`sale` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`sale` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `medicine_id` INT NOT NULL COMMENT '药物表主键',
  `type` INT NULL COMMENT '类型，1售卖，0为退货',
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录日期',
  `count` INT NOT NULL COMMENT '数量',
  `total_price` DECIMAL(9,2) NOT NULL COMMENT '总售价',
  `recorder_id` INT NOT NULL COMMENT '操作人',
  PRIMARY KEY (`id`),
  INDEX `fk_sale_medicine1_idx` (`medicine_id` ASC),
  INDEX `fk_sale_user1_idx` (`recorder_id` ASC),
  CONSTRAINT `fk_sale_medicine1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `pharmacy`.`medicine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_user1`
    FOREIGN KEY (`recorder_id`)
    REFERENCES `pharmacy`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`purchase` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`purchase` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `medicine_id` INT NOT NULL COMMENT '药品表主键',
  `status` INT NULL COMMENT '进行状态，-1表示未开始，0表示进行中，1表示已完成',
  `maker_id` INT NOT NULL COMMENT '采购计划制定者',
  `plan_date` TIMESTAMP NULL COMMENT '采购计划制定事件',
  `executor_id` INT NULL COMMENT '采购计划执行者',
  `planned_quantity` INT NOT NULL COMMENT '计划数量',
  `actual_quantity` INT NULL COMMENT '实际数量',
  `total_price` DECIMAL(9,2) NULL,
  `start_date` DATE NULL COMMENT '开始日期',
  `complete_date` DATE NULL COMMENT '结束日期',
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_medicine1_idx` (`medicine_id` ASC),
  INDEX `fk_purchase_user1_idx` (`maker_id` ASC),
  INDEX `fk_purchase_user2_idx` (`executor_id` ASC),
  CONSTRAINT `fk_purchase_medicine1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `pharmacy`.`medicine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_user1`
    FOREIGN KEY (`maker_id`)
    REFERENCES `pharmacy`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_user2`
    FOREIGN KEY (`executor_id`)
    REFERENCES `pharmacy`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`role` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `name` VARCHAR(45) NULL COMMENT '角色名称',
  `name_zh` VARCHAR(45) NULL COMMENT '角色中文名称',
  `description` VARCHAR(45) NULL COMMENT '角色描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `pharmacy`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pharmacy`.`user_role` ;

CREATE TABLE IF NOT EXISTS `pharmacy`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `user_id` INT NOT NULL COMMENT '用户表主键',
  `role_id` INT NOT NULL COMMENT '角色表主键',
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_user1_idx` (`user_id` ASC),
  INDEX `fk_user_role_role1_idx` (`role_id` ASC),
  UNIQUE INDEX `user_id_role_id_UNIQUE` (`user_id` ASC, `role_id` ASC),
  CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pharmacy`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `pharmacy`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户角色表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
